# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/duchamp/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),duchamp)

$(call add-radio-file-sha1-checked,radio/apusys.img,23e6c254ac7ea688c812357c3edfe75903ff49ee)
$(call add-radio-file-sha1-checked,radio/audio_dsp.img,01c6660e1ca8d48bcf257c233df850cac393fa85)
$(call add-radio-file-sha1-checked,radio/ccu.img,5fa2698b440840a2772a1546aa412e70112ee0cd)
$(call add-radio-file-sha1-checked,radio/connsys_bt.img,a27366c0a9c7b47246f2b51af51a064f5670a6d7)
$(call add-radio-file-sha1-checked,radio/connsys_gnss.img,f75bd55b1e3268209a6cefe27937780603a1cf86)
$(call add-radio-file-sha1-checked,radio/connsys_wifi.img,b0951c7549bc07c7cba6d9ebf0dae4aa38d2a4be)
$(call add-radio-file-sha1-checked,radio/dpm.img,5c09f236a4911b44e9aa0faf0f5b6f5d324b9a1b)
$(call add-radio-file-sha1-checked,radio/gpueb.img,b4cfcf1bc5a7ab0024e3ac40ba875d5e1200801e)
$(call add-radio-file-sha1-checked,radio/gz.img,dfe928eac94f10a3e8b67549ca9c6663716acad4)
$(call add-radio-file-sha1-checked,radio/lk.img,ec662023bc000e1f8f33bd12307ed510fc9f5a4a)
$(call add-radio-file-sha1-checked,radio/mcf_ota.img,d783d3fed80ddc70dd405e9e8a5af6fd626e85a3)
$(call add-radio-file-sha1-checked,radio/mcupm.img,7ffdfa64feb89bde11c4f2a57efdee8f41ed1857)
$(call add-radio-file-sha1-checked,radio/modem.img,af309a916d630a60a13f7751902bae69aa612988)
$(call add-radio-file-sha1-checked,radio/mvpu_algo.img,5c9b559f0bac7aaf95bcffb2173be656649c3161)
$(call add-radio-file-sha1-checked,radio/pi_img.img,9e96e0fc7c627aeb91c16871ece8485cdf7814c7)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,731b19626a5dc71f0eddb9be163dbcbb83bdfe49)
$(call add-radio-file-sha1-checked,radio/scp.img,4f9e55fe09d406d66cdda53f6881d9b865ca3ae9)
$(call add-radio-file-sha1-checked,radio/spmfw.img,e44a8e62e699c8d940353a9ca665a31bbeae8645)
$(call add-radio-file-sha1-checked,radio/sspm.img,f5dddb894059a6897179fc219acf4a2dc858001c)
$(call add-radio-file-sha1-checked,radio/tee.img,e58f3f30c10d7f2ac25c49d8bf331924f66c3f23)
$(call add-radio-file-sha1-checked,radio/vcp.img,3d0c36252deb18861d1a93eb0293207a77438e50)

endif
