# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/duchamp/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),duchamp)

$(call add-radio-file-sha1-checked,radio/apusys.img,29a76fd76c88bd75e6d87ef43b3ed43dbe9b7160)
$(call add-radio-file-sha1-checked,radio/audio_dsp.img,2a0e16434f2026df79fdb461e5685934f9df6405)
$(call add-radio-file-sha1-checked,radio/ccu.img,c9ae942af1553a77927cdd285759c10cfcd7df47)
$(call add-radio-file-sha1-checked,radio/connsys_bt.img,ab991d535b6b1aa70a1f6ea0baff7b0aae53e8bf)
$(call add-radio-file-sha1-checked,radio/connsys_gnss.img,e4ac827a05cac3d604c59da94d64f3e89696b755)
$(call add-radio-file-sha1-checked,radio/connsys_wifi.img,49bddfe6e711a5f50434751a51655e96ac5084ff)
$(call add-radio-file-sha1-checked,radio/dpm.img,505d4991c492daa25b12319e2fea4e39c8dfc47e)
$(call add-radio-file-sha1-checked,radio/gpueb.img,40f7f8a186a35eaa2b9cefc5b315ca7f7a7160cd)
$(call add-radio-file-sha1-checked,radio/gz.img,23670d4a8b90f9d48c31c732801991341bf96666)
$(call add-radio-file-sha1-checked,radio/mcf_ota.img,0dbca210232597bfa55aa6c5c6ab3039e7aa6b2d)
$(call add-radio-file-sha1-checked,radio/mcupm.img,2bdedbe1c6220fb6c1b7a8546b7b1c79d5004325)
$(call add-radio-file-sha1-checked,radio/modem.img,d8c00ede3115e94fb2f57958462f1f43c31de9f8)
$(call add-radio-file-sha1-checked,radio/mvpu_algo.img,c1c1b748ca3b2543eee96320b837709bd584048d)
$(call add-radio-file-sha1-checked,radio/pi_img.img,a1e4994c977fd3641b259e30ffb598ce39f902e4)
$(call add-radio-file-sha1-checked,radio/scp.img,213af3580936297a7fe420b2164913a9f6c8db47)
$(call add-radio-file-sha1-checked,radio/spmfw.img,94532c37d34fe0b2733f74bf6cce19f09f8e1b75)
$(call add-radio-file-sha1-checked,radio/sspm.img,54868c403e7e6ed6ccfc5f735f347e1aac0bbbc4)
$(call add-radio-file-sha1-checked,radio/tee.img,8a3f26e7684377e43f7887ce62c1818857f974e1)
$(call add-radio-file-sha1-checked,radio/vcp.img,1497ee06a225a7301bbc4b9451659f36bd00dfae)

endif
