# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/duchamp/setup-makefiles.sh

AB_OTA_PARTITIONS += \
    apusys \
    audio_dsp \
    ccu \
    connsys_bt \
    connsys_gnss \
    connsys_wifi \
    dpm \
    gpueb \
    gz \
    lk \
    mcf_ota \
    mcupm \
    modem \
    mvpu_algo \
    pi_img \
    preloader_raw \
    scp \
    spmfw \
    sspm \
    tee \
    vcp
